name: 'Workflow'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  backend_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: 'xdebug'
          php-version: 8.4
        env:
          fail-fast: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: '~/.cache/composer'
          key: "cache-composer-${{ hashFiles('**/app/composer.lock') }}"
          restore-keys: 'cache-composer-'

      - name: Install dependencies
        working-directory: backend
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Run unit tests
        working-directory: backend
        run: composer run tests:unit:ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./backend/reports/coverage.xml
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./backend/reports/junit-unittests.xml

  lint_docker_compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: lint docker-compose.yml
        run: docker compose config

  frontend_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Run ESLint
        working-directory: frontend
        run: npm run lint:ts

  frontend_npm_build:
    runs-on: ubuntu-latest
    needs:
      - frontend_lint
      - frontend_security_checks
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: npm run build
        working-directory: frontend
        run: npm run build

  frontend_security_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Run npm audit
        working-directory: frontend
        run: npm audit --audit-level=low

  security_checks_backend:
    name: security-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: The PHP Security Checker
        uses: symfonycorp/security-checker-action@v5
        id: security-check
        with:
          lock: backend/composer.lock

  static_analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check_command: ['lint:composer', 'lint:php', 'phpstan']
        php_version: ['8.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: 'xdebug'
          php-version: ${{ matrix.php_version }}
        env:
          fail-fast: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: '~/.cache/composer'
          key: "cache-composer-${{ hashFiles('**/app/composer.lock') }}"
          restore-keys: 'cache-composer-'

      - name: Install dependencies
        working-directory: backend
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Run ${{ matrix.check_command }}
        working-directory: backend
        run: composer run ${{ matrix.check_command }}

  api_tests:
    runs-on: ubuntu-latest
    needs:
      - static_analysis
      - security_checks_backend
      - backend_unit_tests
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: symfony
          MYSQL_DATABASE: symfony
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          extensions: mbstring, xml, ctype, iconv, intl, mysqli, pdo, pdo_mysql, posix, pcntl, mysql
          coverage: 'xdebug'
          php-version: 8.4
        env:
          fail-fast: true

      - name: Get composer cache directory
        id: composer-cache
        working-directory: backend
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        working-directory: backend
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Prepare database
        working-directory: backend
        run: composer run db:recreate:test
        env:
          DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony?serverVersion=8.2

      - name: Create JWT
        working-directory: backend
        run: php bin/console lexik:jwt:generate-keypair --skip-if-exists

      - name: Run api tests
        working-directory: backend
        env:
          DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony?serverVersion=8.2
        run: composer run tests:api:ci

  build_backend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - static_analysis
      - security_checks_backend
      - backend_unit_tests
      - api_tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.REGISTRY_TOKEN}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          target: build_prod
          push: true
          tags: ghcr.io/var-lab-it/opencal:backend-latest-unstable

  build_backend_nginx:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - static_analysis
      - security_checks_backend
      - backend_unit_tests
      - api_tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.REGISTRY_TOKEN}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          target: nginx
          push: true
          tags: ghcr.io/var-lab-it/opencal:backend-nginx-latest-unstable

  build_frontend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - frontend_npm_build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.REGISTRY_TOKEN}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          target: production
          push: true
          tags: ghcr.io/var-lab-it/opencal:frontend-latest-unstable

#  e2e-tests:
#    runs-on: ubuntu-latest
##    needs:
##      - api_tests
#    #    needs:
##      - build_backend
##      - build_nginx
##      - build_frontend
##    services:
##      database:
##        image: mysql:8.2
##        env:
##          MYSQL_ROOT_PASSWORD: symfony
##          MYSQL_USER: symfony
##          MYSQL_PASSWORD: symfony
##          MYSQL_DATABASE: symfony
##      backend:
##        image: ghcr.io/var-lab-it/opencal:backend-${{ github.run_id }}
##        env:
##          MYSQL_HOST: database
##      nginx:
##        image: ghcr.io/var-lab-it/opencal:nginx-${{ github.run_id }}
##        ports:
##          - 8080:80
#    services:
#      mysql:
#        image: mysql:latest
#        env:
#          MYSQL_ALLOW_EMPTY_PASSWORD: false
#          MYSQL_ROOT_PASSWORD: symfony
#          MYSQL_DATABASE: symfony
#        ports:
#          - 3306/tcp
#        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Install PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          extensions: mbstring, xml, ctype, iconv, intl, mysqli, pdo, pdo_mysql, posix, pcntl, mysql
#          coverage: 'xdebug'
#          php-version: 8.4
#        env:
#          fail-fast: true
#
#      - name: Get composer cache directory
#        id: composer-cache
#        working-directory: backend
#        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
#
#      - name: Cache composer dependencies
#        uses: actions/cache@v3
#        with:
#          path: ${{ steps.composer-cache.outputs.dir }}
#          # Use composer.json for key, if composer.lock is not committed.
#          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
#          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
#          restore-keys: ${{ runner.os }}-composer
#
#      - name: Install backend dependencies
#        working-directory: backend
#        run: composer install --prefer-dist --no-interaction --no-progress
#
#      - name: Prepare database
#        working-directory: backend
#        run: composer run db:recreate:dev
#        env:
#          DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony?serverVersion=8.2
#
#      - name: Create JWT
#        working-directory: backend
#        run: php bin/console lexik:jwt:generate-keypair --skip-if-exists
#
#      - name: Install Symfony cli 1
#        run: curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh' | sudo -E bash
#
#      - name: Install Symfony cli 2
#        run: sudo apt install symfony-cli
#
#      - name: Run symfony server
#        working-directory: backend
#        env:
#          DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony?serverVersion=8.2
#        run: symfony server:start -d --port=8080 --allow-http --no-tls
#
#      - name: Check api is available
#        run: |
#          curl -X POST -H "Content-Type: application/json" http://localhost:8080/auth -d '{"email":"user@example.tld","password":"password"}'
#
#      - name: Install frontend dependencies
#        working-directory: frontend
#        run: npm ci
#
#      - name: Start Vue dev server
#        working-directory: frontend
#        run: npm run dev &
#
#      - name: Check frontend is available
#        run: |
#          curl -X GET -H "Content-Type: application/json" http://localhost:5173/
#
#      - name: Install e2e dependencies
#        working-directory: e2e
#        run: npm ci
#
#      - name: Run Cypress tests
#        working-directory: e2e
#        run: CYPRESS_BASE_URL=http://localhost:5173/ npm run cy:run
